### ISSUE TITLE
Support SSH connection

### ISSUE THREAD

**Issue by jschmersal** [TouK/sputnik#107]
This is a big ask, I'm sure, but SSH connection support would be great, as it can be problematic having usernames/passwords embedded in sputnik config files (for non-interactive users like our Jenkins user).

I see that [gerrit-events](https://github.com/sonyxperiadev/gerrit-events) has ssh support... If I can find some spare time I'll try to submit a pull request.

**Comment by anomalizer** [comment]
gerrit-event seems to be designed to listen to the event stream. That is a different feature request from merely using ssh for fetching patchsets and posting comments.

**Comment by SpOOnman** [comment]
You are right @anomalizer, Sputnik uses different model.
