### ISSUE TITLE
Prevent duplicate comments in Gerrit

### ISSUE THREAD

**Issue by lazyfiend** [TouK/sputnik#108]
Added post build step to run sputnik in Jenkins with Gerrit Trigger. 

When we retrigger the patchset using Gerrit Trigger, sputnik is also executed against the same patchset. This causes the comments in Gerrit added by sputnik to be added again.

I would like to request for a way to prevent it inside sputnik.

**Comment by SpOOnman** [comment]
We're aware of that. This change would reguire additional calls to Gerrit to fetch actual comments and compare them. Pull request is very welcome!

**Comment by lazyfiend** [comment]
I see. I might check it if i have the time.

**Comment by vitas** [comment]
would be great to get it done

**Comment by corebonts** [comment]
There's a gerrit feature _omitDuplicateComments_ which can be set on _ReviewInput_. (see my commit)
It's good because this way there's no need for the additional Gerrit call.

**Comment by SpOOnman** [comment]
It is fixed in #230 and released with 2.6.0.
