### ISSUE TITLE
Project's logo

### ISSUE THREAD

**Issue by zygm0nt** [TouK/sputnik#11]
Would be nice to have one! :)

**Comment by zygm0nt** [comment]
Let's choose a logo or close this issue as irrelevant. I'd go with one of the logos I've proposed on Jun 30.

**Comment by pjagielski** [comment]
+1, this one for me

![screen shot 2015-02-20 at 10 39 58](https://cloud.githubusercontent.com/assets/513361/6284074/dc691f32-b8ec-11e4-9a09-8bb928d691ff.png)

**Comment by zygm0nt** [comment]
It's fine for me too.

**Comment by pjagielski** [comment]
@SpOOnman ?

**Comment by SpOOnman** [comment]
Ok, let's use this one. So what do we do with it now? :D

**Comment by pjagielski** [comment]
Added logo to readme

**Comment by SpOOnman** [comment]
Thanks!
