### ISSUE TITLE
GerritException: Error when setting review

### ISSUE THREAD

**Issue by tigerlcq** [TouK/sputnik#112]
hi,
     I meet a problem, it occur in sputnik 1.5.0, and sputnik 1.4.0 has not this issue.
     I setup a gerrit + jenkins + sputnik system (gerrit and jenkins are deployed at 2 PCs), it worked fine with version 1.4.0 except that some known bugs. I was exciting to get new version news, but after I changed sputnit to version 1.5.0, it cannot work.
This is part of log:

14:31:41.978 [main] INFO  p.t.s.e.v.score.ScoreAlwaysPass - Adding static passing score {Code-Review=1} to review
Exception in thread "main" pl.touk.sputnik.connector.gerrit.GerritException: Error when setting review
	at pl.touk.sputnik.connector.gerrit.GerritFacade.setReview(GerritFacade.java:72)
	at pl.touk.sputnik.engine.Engine.run(Engine.java:44)
	at pl.touk.sputnik.Main.main(Main.java:36)
Caused by: com.urswolfer.gerrit.client.rest.http.HttpStatusException: Request not successful. Message: Forbidden. Status-Code: 403. Content: Invalid authentication method. In order to authenticate, prefix the REST endpoint URL with /a/ (e.g. http://example.com/a/projects/)..
	at com.urswolfer.gerrit.client.rest.http.GerritRestClient.checkStatusCode(GerritRestClient.java:359)
	at com.urswolfer.gerrit.client.rest.http.GerritRestClient.request(GerritRestClient.java:121)
	at com.urswolfer.gerrit.client.rest.http.GerritRestClient.postRequest(GerritRestClient.java:102)
	at com.urswolfer.gerrit.client.rest.http.changes.RevisionApiRestClient.review(RevisionApiRestClient.java:65)
	at pl.touk.sputnik.connector.gerrit.GerritFacade.setReview(GerritFacade.java:69)
	... 2 more
Build step 'Execute shell' marked build as failure
Finished: FAILURE

    I  found a strange thing, maybe this will help you to fix the bug. I also setup a test environment:  gerrit and jenkins are deployed at the same PC. Both version 1.4.0 and version 1.5.0 worked very well in this case.

      thank you

Tiger

**Comment by imsandli** [comment]
I'm facing the same issue with sputnik 1.5.0

1.4.0 works fine.

Gerrit version is 2.11.3

**Comment by tigerlcq** [comment]
I doubt URL of new version sputnik voting is "localhost" rather than URL in configuration file.

**Comment by SpOOnman** [comment]
We've switched to @uwolfer library. There is a problem with URL, so I guess Gerrit client is not configured properly. @uwolfer can you give us a hint?

**Comment by SpOOnman** [comment]
Can you paste your Using Gerrit URL log line? Is it correct?

**Comment by uwolfer** [comment]
@tigerlcq: As @SpOOnman wrote: please post all relevant config lines (probably anonymized).

**Comment by imsandli** [comment]
Relevant section of the config file

    connector.type=gerrit
    connector.useHttps=true
    connector.host=hostname.com
    connector.port=8443
    connector.username=gerrit-user
    connector.password=***********
    score.strategy=NoScore
    global.maxNumberOfComments=25


Relevant part of the log

    ../sputnik-1.5.0/bin/sputnik --conf /sputnik.properties --changeId 1 --revisionId asdfxxxxxxxxxxxxxxxxxx
    Sputnik version 1.5.0
    08:43:39.703 [main] INFO  p.t.s.c.ConfigurationBuilder - Initializing configuration properties from file /../sputnik/sputnik.properties
    08:43:39.797 [main] INFO  p.t.s.c.gerrit.GerritFacadeBuilder - Using Gerrit URL: https://hostname.com:8443
    08:43:53.114 [main] INFO  pl.touk.sputnik.engine.ReviewRunner - Review started for processor Checkstyle
    08:43:53.117 [main] INFO  p.t.s.r.filter.FileExtensionFilter - Filtering out review files with allowed extensions [java]
    ....
    08:43:53.118 [main] INFO  p.t.s.r.filter.FileExtensionFilter - Total 4 of 7 files had allowed extensions [java]
    08:43:53.144 [main] INFO  p.t.s.p.c.CheckstyleProcessor - Using Checkstyle configuration file ../sputnik/conf/checkstyle.xml
    08:43:53.885 [main] INFO  p.t.s.p.checkstyle.CollectorListener - Checktyle audit started
    08:43:54.459 [main] INFO  p.t.s.p.checkstyle.CollectorListener - Checktyle audit finished
    08:43:54.471 [main] INFO  pl.touk.sputnik.engine.ReviewRunner - Review finished for processor Checkstyle. Took 1 s
    08:43:54.471 [main] INFO  pl.touk.sputnik.engine.ReviewRunner - Review for processor Checkstyle returned 0 violations
    08:43:54.471 [main] INFO  pl.touk.sputnik.engine.ReviewRunner - Review started for processor PMD
    08:43:54.473 [main] INFO  p.t.s.r.filter.FileExtensionFilter - Filtering out review files with allowed extensions [java, .class, properties, js, xml, xsl, c, h, cc, cpp, cxx, c++, hh, hpp, hxx, h++, c, h, cpp, hpp, cxx, hxx, cs, php, phtml, php3, php4, php5, phps, rb, rbw, f, for, f90, f95]
    ....
    Sep 24, 2015 8:43:55 AM net.sourceforge.pmd.renderers.RendererFactory createRenderer
    WARNING: The renderer uses a deprecated mechanism to use the properties. Please define the needed properties with this.definePropertyDescriptor(..).
    08:43:55.424 [main] INFO  p.t.s.p.pmd.CollectorRenderer - PMD audit started
    08:43:57.282 [main] INFO  p.t.s.p.pmd.CollectorRenderer - PMD audit finished
    08:43:57.282 [main] INFO  pl.touk.sputnik.engine.ReviewRunner - Review finished for processor PMD. Took 2 s
    08:43:57.282 [main] INFO  pl.touk.sputnik.engine.ReviewRunner - Review for processor PMD returned 2 violations
    08:43:57.309 [main] INFO  p.t.s.e.v.SummaryMessageVisitor - Adding summary message to review: Total 2 violations found
    08:43:57.309 [main] INFO  p.t.s.e.visitor.LimitCommentVisitor - There are 2 total violations for this review, which is below maximum comment count 25. No comments are filtered
    08:43:57.309 [main] INFO  p.t.s.engine.visitor.score.NoScore - No score for review
    Exception in thread "main" pl.touk.sputnik.connector.gerrit.GerritException: Error when setting review
            at pl.touk.sputnik.connector.gerrit.GerritFacade.setReview(GerritFacade.java:72)
            at pl.touk.sputnik.engine.Engine.run(Engine.java:44)
            at pl.touk.sputnik.Main.main(Main.java:36)
    Caused by: com.urswolfer.gerrit.client.rest.http.HttpStatusException: Request not successful. Message: Forbidden. Status-Code: 403. Content: Invalid authentication method. In order to authenticate, prefix the REST endpoint URL with /a/ (e.g. http://example.com/a/projects/)..
            at com.urswolfer.gerrit.client.rest.http.GerritRestClient.checkStatusCode(GerritRestClient.java:359)
            at com.urswolfer.gerrit.client.rest.http.GerritRestClient.request(GerritRestClient.java:121)
            at com.urswolfer.gerrit.client.rest.http.GerritRestClient.postRequest(GerritRestClient.java:102)
            at com.urswolfer.gerrit.client.rest.http.changes.RevisionApiRestClient.review(RevisionApiRestClient.java:65)
            at pl.touk.sputnik.connector.gerrit.GerritFacade.setReview(GerritFacade.java:69)

Just ask if you need more information or if i can help debugging it.

**Comment by tigerlcq** [comment]
My config file is

connector.type=gerrit
connector.host=10.1.11.15
connector.port=8085
connector.path=
connector.username=jenkins
connector.password=Vc8xNzSuLxDzec7R4JRZom7O7gkm+99KR/8gmrTvSg
connector.useHttps=false
checkstyle.enabled=true
checkstyle.configurationFile=/opt/sputnik/putao_checks.xml
checkstyle.propertiesFile=
pmd.enabled=true
pmd.ruleSets=
findbugs.enabled=true
findbugs.includeFilter=/opt/sputnik/sonar-findbugs.xml
findbugs.excludeFilter=/opt/sputnik/findbugs-exclude.xml

**Comment by tigerlcq** [comment]
log in sputnik 1.5.0:

+ /opt/sputnik/150/bin/sputnik --conf /opt/sputnik/test.properties --changeId Iec8fcbb7fab7009d6c32dfa398ad3f610ea89ae9 --revisionId 5b04962c108d3a5f015110e41c101f0500773ab8
Sputnik version 1.5.0
17:59:37.385 [main] INFO  p.t.s.c.ConfigurationBuilder - Initializing configuration properties from file /opt/sputnik/test.properties
17:59:37.402 [main] INFO  p.t.s.c.gerrit.GerritFacadeBuilder - Using Gerrit URL: http://10.1.11.15:8085
17:59:39.092 [main] INFO  pl.touk.sputnik.engine.ReviewRunner - Review started for processor Checkstyle
17:59:39.094 [main] INFO  p.t.s.r.filter.FileExtensionFilter - Filtering out review files with allowed extensions [java]
17:59:39.094 [main] INFO  p.t.s.r.filter.FileExtensionFilter - Total 1 of 1 files had allowed extensions [java]
17:59:39.102 [main] INFO  p.t.s.p.c.CheckstyleProcessor - Using Checkstyle configuration file /opt/sputnik/putao_checks.xml
17:59:39.650 [main] INFO  p.t.s.p.checkstyle.CollectorListener - Checktyle audit started
17:59:40.277 [main] INFO  p.t.s.p.checkstyle.CollectorListener - Checktyle audit finished
17:59:40.277 [main] INFO  pl.touk.sputnik.engine.ReviewRunner - Review finished for processor Checkstyle. Took 1 s
17:59:40.277 [main] INFO  pl.touk.sputnik.engine.ReviewRunner - Review for processor Checkstyle returned 10 violations
17:59:40.278 [main] INFO  pl.touk.sputnik.engine.ReviewRunner - Review started for processor PMD
17:59:40.279 [main] INFO  p.t.s.r.filter.FileExtensionFilter - Filtering out review files with allowed extensions [java, .class, properties, js, xml, xsl, c, h, cc, cpp, cxx, c++, hh, hpp, hxx, h++, c, h, cpp, hpp, cxx, hxx, cs, php, phtml, php3, php4, php5, phps, rb, rbw, f, for, f90, f95]
17:59:40.279 [main] INFO  p.t.s.r.filter.FileExtensionFilter - Total 1 of 1 files had allowed extensions [java, .class, properties, js, xml, xsl, c, h, cc, cpp, cxx, c++, hh, hpp, hxx, h++, c, h, cpp, hpp, cxx, hxx, cs, php, phtml, php3, php4, php5, phps, rb, rbw, f, for, f90, f95]
17:59:40.283 [main] INFO  p.t.s.processor.pmd.PmdProcessor - Using PMD rulesets rulesets/java/basic.xml
Sep 24, 2015 5:59:40 PM net.sourceforge.pmd.renderers.RendererFactory createRenderer
WARNING: The renderer uses a deprecated mechanism to use the properties. Please define the needed properties with this.definePropertyDescriptor(..).
17:59:40.547 [main] INFO  p.t.s.p.pmd.CollectorRenderer - PMD audit started
17:59:40.944 [main] INFO  p.t.s.p.pmd.CollectorRenderer - PMD audit finished
17:59:40.944 [main] INFO  pl.touk.sputnik.engine.ReviewRunner - Review finished for processor PMD. Took 0 s
17:59:40.944 [main] INFO  pl.touk.sputnik.engine.ReviewRunner - Review for processor PMD returned 0 violations
17:59:40.948 [main] INFO  p.t.s.e.v.SummaryMessageVisitor - Adding summary message to review: Total 10 violations found
17:59:40.950 [main] INFO  p.t.s.e.v.score.ScoreAlwaysPass - Adding static passing score {Code-Review=1} to review
Exception in thread "main" pl.touk.sputnik.connector.gerrit.GerritException: Error when setting review
	at pl.touk.sputnik.connector.gerrit.GerritFacade.setReview(GerritFacade.java:72)
	at pl.touk.sputnik.engine.Engine.run(Engine.java:44)
	at pl.touk.sputnik.Main.main(Main.java:36)
Caused by: com.urswolfer.gerrit.client.rest.http.HttpStatusException: Request not successful. Message: Forbidden. Status-Code: 403. Content: Invalid authentication method. In order to authenticate, prefix the REST endpoint URL with /a/ (e.g. http://example.com/a/projects/)..
	at com.urswolfer.gerrit.client.rest.http.GerritRestClient.checkStatusCode(GerritRestClient.java:359)
	at com.urswolfer.gerrit.client.rest.http.GerritRestClient.request(GerritRestClient.java:121)
	at com.urswolfer.gerrit.client.rest.http.GerritRestClient.postRequest(GerritRestClient.java:102)
	at com.urswolfer.gerrit.client.rest.http.changes.RevisionApiRestClient.review(RevisionApiRestClient.java:65)
	at pl.touk.sputnik.connector.gerrit.GerritFacade.setReview(GerritFacade.java:69)
	... 2 more
Build step 'Execute shell' marked build as failure
Finished: FAILURE

**Comment by tigerlcq** [comment]
log in sputnik 1.4.0 with the same gerrit configure and the same sputnik configure:

+ /opt/sputnik/bin/sputnik --conf /opt/sputnik/test.properties --changeId I7758399c707b5a785d8ba938fce098f7c95fb76a --revisionId 9faa7a9e07bfc25a029af605b3692acf8295b8ab
Sputnik version 1.4.0
17:57:04.464 [main] INFO  p.t.s.c.ConfigurationHolder - Initializing configuration properties from file /opt/sputnik/test.properties
17:57:04.971 [main] INFO  p.t.s.connector.http.HttpConnector - Request  1: GET to http://10.1.11.15:8085/a/changes/I7758399c707b5a785d8ba938fce098f7c95fb76a/revisions/9faa7a9e07bfc25a029af605b3692acf8295b8ab/files/?
17:57:05.019 [main] ERROR o.a.http.impl.auth.HttpAuthenticator - DIGEST [complete=false, nonce=null, nc=0] authentication error: missing realm in challenge
17:57:05.046 [main] INFO  p.t.s.connector.http.HttpConnector - Response 1: HTTP/1.1 200 OK
17:57:05.048 [main] INFO  p.t.s.connector.http.HttpConnector - Entity 1: )]}'
{
  "/COMMIT_MSG": {
    "status": "A",
    "lines_inserted": 10
  },
  "Application/src/main/java/com/example/android/cardview/CardViewActivity.java": {
    "lines_inserted": 1
  }
}

17:57:05.119 [main] INFO  pl.touk.sputnik.engine.ReviewRunner - Review started for processor Checkstyle
17:57:05.120 [main] INFO  p.t.s.r.filter.FileExtensionFilter - Filtering out review files with allowed extensions [java]
17:57:05.120 [main] INFO  p.t.s.r.filter.FileExtensionFilter - Total 1 of 1 files had allowed extensions [java]
17:57:05.138 [main] INFO  p.t.s.p.c.CheckstyleProcessor - Using Checkstyle configuration file /opt/sputnik/putao_checks.xml
17:57:05.686 [main] INFO  p.t.s.p.checkstyle.CollectorListener - Checktyle audit started
17:57:06.320 [main] INFO  p.t.s.p.checkstyle.CollectorListener - Checktyle audit finished
17:57:06.320 [main] INFO  pl.touk.sputnik.engine.ReviewRunner - Review finished for processor Checkstyle. Took 1 s
17:57:06.320 [main] INFO  pl.touk.sputnik.engine.ReviewRunner - Review for processor Checkstyle returned 10 violations
17:57:06.322 [main] INFO  pl.touk.sputnik.engine.ReviewRunner - Review started for processor PMD
17:57:06.327 [main] INFO  p.t.s.processor.pmd.PmdProcessor - Using PMD rulesets rulesets/java/basic.xml
17:57:06.328 [main] INFO  p.t.s.r.filter.FileExtensionFilter - Filtering out review files with allowed extensions [java, .class, properties, js, xml, xsl, c, h, cc, cpp, cxx, c++, hh, hpp, hxx, h++, c, h, cpp, hpp, cxx, hxx, cs, php, phtml, php3, php4, php5, phps, rb, rbw, f, for, f90, f95]
17:57:06.328 [main] INFO  p.t.s.r.filter.FileExtensionFilter - Total 1 of 1 files had allowed extensions [java, .class, properties, js, xml, xsl, c, h, cc, cpp, cxx, c++, hh, hpp, hxx, h++, c, h, cpp, hpp, cxx, hxx, cs, php, phtml, php3, php4, php5, phps, rb, rbw, f, for, f90, f95]
17:57:06.597 [main] INFO  p.t.s.p.pmd.CollectorRenderer - PMD audit started
17:57:07.040 [main] INFO  p.t.s.p.pmd.CollectorRenderer - PMD audit finished
17:57:07.040 [main] INFO  pl.touk.sputnik.engine.ReviewRunner - Review finished for processor PMD. Took 0 s
17:57:07.040 [main] INFO  pl.touk.sputnik.engine.ReviewRunner - Review for processor PMD returned 0 violations
17:57:07.044 [main] INFO  p.t.s.e.v.SummaryMessageVisitor - Adding summary message to review: Total 10 violations found
17:57:07.046 [main] INFO  p.t.s.e.v.score.ScoreAlwaysPass - Adding static passing score {Code-Review=1} to review
17:57:07.080 [main] INFO  p.t.s.c.gerrit.GerritConnector - Setting review {"message":"Total 10 violations found","labels":{"Code-Review":1},"comments":{"Application/src/main/java/com/example/android/cardview/CardViewActivity.java":[{"message":"[Checkstyle] WARNING: Line contains a tab character.","line":29},{"message":"[Checkstyle] WARNING: Line contains a tab character.","line":30},{"message":"[Checkstyle] WARNING: Line contains a tab character.","line":32},{"message":"[Checkstyle] WARNING: WhitespaceAround: 'for' is not followed by whitespace. Empty blocks may only be represented as {} when not part of a multi-block statement (4.1.3)","line":32},{"message":"[Checkstyle] WARNING: 'for' child have incorrect indentation level 16, expected level should be 12.","line":33},{"message":"[Checkstyle] WARNING: Line has trailing spaces.","line":33},{"message":"[Checkstyle] WARNING: Line contains a tab character.","line":33},{"message":"[Checkstyle] WARNING: Line contains a tab character.","line":34},{"message":"[Checkstyle] WARNING: Line contains a tab character.","line":35},{"message":"[Checkstyle] WARNING: 'METHOD_DEF' should be separated from previous statement.","line":37}]}}
17:57:07.082 [main] INFO  p.t.s.connector.http.HttpConnector - Request  2: POST to http://10.1.11.15:8085/a/changes/I7758399c707b5a785d8ba938fce098f7c95fb76a/revisions/9faa7a9e07bfc25a029af605b3692acf8295b8ab/review?
17:57:07.127 [main] INFO  p.t.s.connector.http.HttpConnector - Response 2: HTTP/1.1 200 OK
17:57:07.127 [main] INFO  p.t.s.connector.http.HttpConnector - Entity 2: )]}'
{
  "labels": {
    "Code-Review": 1
  }
}

+ echo exit 0 workaround
exit 0 workaround
Finished: SUCCESS

**Comment by uwolfer** [comment]
@tigerlcq and @imsandli: What's the URL you are using in your browser for accessing Gerrit? Do the users you are using for Sputnik have a HTTP password generated?

**Comment by imsandli** [comment]
@uwolfer Sputnik is the only "user" using a http password. All other users are authenticated against a LDAP.

**Comment by tigerlcq** [comment]
@uwolfer My case is the same as @imsandli

**Comment by tigerlcq** [comment]
@uwolfer Both Jenkins and Sputnik use the same user of Gerrit, and the user's password is from HTTP password generated in Gerrit.

**Comment by uwolfer** [comment]
If you have set up Gerrit by yourself, it would help me if you could post Gerrit settings file so I can try to reproduce your issues with an almost identical setup.

**Comment by SpOOnman** [comment]
@uwolfer I think that problem lies within library that connects to Gerrit. Problem is that we don't know what URL it uses. Apparently it uses wrong URL or wrong authorisation scheme. Gerrit responds 403. I suspect that there is no /a/ included in path. It would be great if you can check that and log URL your library uses to connect to Gerrit.

**Comment by tigerlcq** [comment]
@uwolfer My Gerrit server is in 10.1.11.15, Apache revert proxy and sputnik is in 10.1.11.16. There is my config file of Gerrit

[gerrit]
	basePath = git
        canonicalWebUrl =http://10.1.11.16/
[database]
	type = h2
	database = db/ReviewDB
[index]
	type = LUCENE
[auth]
	type = HTTP
[sendemail]
	smtpServer = mail.xxxx.com
	smtpServerPort = 587
	smtpEncryption = TLS
	smtpUser = gerrit@xxxx.com
	sslVerify = false
	from = CodeReview<gerrit@xxxx.com>
[container]
	user = root
	javaHome = /usr/lib/jvm/java-7-openjdk-amd64/jre
[sshd]
	listenAddress = 10.1.11.15:29418
[httpd]
	listenUrl = proxy-http://10.1.11.15:8085/
[cache]
	directory = cache
[gitweb]
        cgi=/usr/share/gitweb/gitweb.cgi

**Comment by uwolfer** [comment]
@SpOOnman: You can find the URL it uses in the logs above. It looks right, but something with authentication seems to be wrong.

@tigerlcq: Do you have configured the Apache reverse proxy exactly like documented in Gerrit documentation?

**Comment by SpOOnman** [comment]
@uwolfer I cannot find URL in this snippet. It only describes a suggestion with an example URL:

> 17:59:40.950 [main] INFO p.t.s.e.v.score.ScoreAlwaysPass - Adding static passing score {Code-Review=1} to review Exception in thread "main" pl.touk.sputnik.connector.gerrit.GerritException: Error when setting review at pl.touk.sputnik.connector.gerrit.GerritFacade.setReview(GerritFacade.java:72) at pl.touk.sputnik.engine.Engine.run(Engine.java:44) at pl.touk.sputnik.Main.main(Main.java:36) Caused by: com.urswolfer.gerrit.client.rest.http.HttpStatusException: Request not successful. Message: Forbidden. Status-Code: 403. Content: Invalid authentication method. In order to authenticate, prefix the REST endpoint URL with /a/ (e.g. http://example.com/a/projects/).. at com.urswolfer.gerrit.client.rest.http.GerritRestClient.checkStatusCode(GerritRestClient.java:359) at com.urswolfer.gerrit.client.rest.http.GerritRestClient.request(GerritRestClient.java:121) at com.urswolfer.gerrit.client.rest.http.GerritRestClient.postRequest(GerritRestClient.java:102) at com.urswolfer.gerrit.client.rest.http.changes.RevisionApiRestClient.review(RevisionApiRestClient.java:65) at pl.touk.sputnik.connector.gerrit.GerritFacade.setReview(GerritFacade.java:69)

I says "Request not successful. Message: Forbidden. Status-Code: 403". But it doesn't print actual URL it used.

**Comment by tigerlcq** [comment]
@uwolfer This my Apache config. It will work well after you modify "AuthUserFile", "ProxyPass" and " ProxyPassReverse" according to your environment.

<VirtualHost *:80>  
     ProxyRequests Off  
     ProxyVia Off  
     ProxyPreserveHost On  
	  
     <Proxy *>  
          Order deny,allow  
	  Allow from all  
     </Proxy>  
   
<Location /login/>  
     AuthType Basic  
     AuthName "Gerrit Code Review"  
     AuthBasicProvider file	
     AuthUserFile /home/xxxx/htpasswd.config
     Require valid-user  
</Location>  
     AllowEncodedSlashes On 	  
     ProxyPass / http://10.1.11.15:8085/  nocanon
     ProxyPassReverse / http://10.1.11.15:8085/
</VirtualHost>

**Comment by imsandli** [comment]
FYI: Our gerrit is NOT behind a Proxy.

I've managed to run sputnik in eclipse to debug it:

the first call which list the files works:

    uri: https://gerrit-host:8443/a/changes/2525/revisions/<REVISION-ID>/files
    httpContext: {http.request=POST /login/ HTTP/1.1 [Content-Length: 44, Content-Type: application/x-www-form-urlencoded; charset=UTF-8, Host: gerrit-host:8443, Connection: Keep-Alive, User-Agent: gerrit-rest-java-client/0.8.1 using Apache-HttpClient/4.3.5 (java 1.5), Accept-Encoding: gzip,deflate, Authorization: Basic bGRhcHVzZXJkb2t1d2lraTpsZGFwMldJS0k=], http.request-config=, expectContinueEnabled=false, proxy=null, localAddress=null, staleConnectionCheckEnabled=true, cookieSpec=null, redirectsEnabled=true, relativeRedirectsAllowed=true, maxRedirects=50, circularRedirectsAllowed=false, authenticationEnabled=true, targetPreferredAuthSchemes=null, proxyPreferredAuthSchemes=null, connectionRequestTimeout=30000, connectTimeout=30000, socketTimeout=30000], http.auth.proxy-scope=state:UNCHALLENGED;, preemptive-auth=BASIC, http.request_sent=true, http.auth.credentials-provider={<any realm>=[principal: gerrit-user]}, http.cookie-spec=best-match, http.cookie-store=[[version: 0][name: GerritAccount][value: aTEfprqvOWDRmKgIWMfOTEFrBvJyBKtZma][domain: gerrit-host][path: /][expiry: null]], http.connection=CPoolProxy{detached}, http.auth.target-scope=state:UNCHALLENGED;auth scheme:basic;credentials present, http.cookiespec-registry={standard=org.apache.http.impl.cookie.RFC2965SpecFactory@fb9c7aa, netscape=org.apache.http.impl.cookie.NetscapeDraftSpecFactory@4c398c80, rfc2109=org.apache.http.impl.cookie.RFC2109SpecFactory@7fc6de5b, rfc2965=org.apache.http.impl.cookie.RFC2965SpecFactory@21baa903, best-match=org.apache.http.impl.cookie.BestMatchSpecFactory@607fbe09, ignorecookies=org.apache.http.impl.cookie.IgnoreSpecFactory@60a2630a, compatibility=org.apache.http.impl.cookie.BrowserCompatSpecFactory@29df4d43}, http.target_host=https://gerrit-host:8443, http.route={s}->https://gerrit-host:8443, http.cookie-origin=[(secure)gerrit-host:8443/login/], http.response=HttpResponseProxy{HTTP/1.1 302 Found [Date: Wed, 30 Sep 2015 08:38:19 GMT, Cache-Control: no-cache, no-store, max-age=0, must-revalidate, Pragma: no-cache, Expires: Thu, 01 Jan 1970 00:00:00 GMT, Set-Cookie: GerritAccount=aTEfprqvOWDRmKgIWMfOTEFrBvJyBKtZma;Path=/, Location: https://gerrit-host:8443/, Content-Length: 0]}, http.authscheme-registry={negotiate=org.apache.http.impl.auth.SPNegoSchemeFactory@5dd91bca, ntlm=org.apache.http.impl.auth.NTLMSchemeFactory@40cb698e, digest=org.apache.http.impl.auth.DigestSchemeFactory@3382f8ae, kerberos=org.apache.http.impl.auth.KerberosSchemeFactory@60641ec8, basic=org.apache.http.impl.auth.BasicSchemeFactory@75f65e45}}
    response: HttpResponseProxy{HTTP/1.1 200 OK [Date: Wed, 30 Sep 2015 08:46:51 GMT, Content-Disposition: attachment, X-Content-Type-Options: nosniff, ETag: 108669e90fe09f71db35ee46063a1d87, Expires: Wed, 30 Sep 2015 08:46:51 GMT, Cache-Control: private, max-age=604800, Content-Type: application/json; charset=UTF-8]}

    loginCache.getHostSupportsGerritAuth(); returns true
    findGerritAccountCookie(); returns absent
    tryGerritHttpFormAuth 
    gerritAccountCookie.isPresent() true but it doesn't MATCH the GERRIT_AUTH_PATTERN 
    login response: HttpResponseProxy{HTTP/1.1 302 Found [Date: Wed, 30 Sep 2015 09:06:32 GMT, Cache-Control: no-cache, no-store, max-age=0, must-revalidate, Pragma: no-cache, Expires: Thu, 01 Jan 1970 00:00:00 GMT, Set-Cookie: GerritAccount=aTEfprtxq3uQlwkXo32fQy67EUUDzXSl6a;Path=/, Location: https://gerrit-host:8443/, Content-Length: 0]}


call to set review -> 

    uri: https://gerrit-host:8443/a/changes/2525/revisions/<REVISION-ID>/review
    httpContext: {http.cookie-store=[[version: 0][name: GerritAccount][value: aTEfprqvOWDRmKgIWMfOTEFrBvJyBKtZma][domain: gerrit-host][path: /][expiry: null]], preemptive-auth=BASIC}
    response: HttpResponseProxy{HTTP/1.1 403 Forbidden [Date: Wed, 30 Sep 2015 08:45:41 GMT, Content-Disposition: attachment, X-Content-Type-Options: nosniff, Cache-Control: no-cache, no-store, max-age=0, must-revalidate, Pragma: no-cache, Expires: Fri, 01 Jan 1990 00:00:00 GMT, Content-Type: text/plain; charset=UTF-8, Transfer-Encoding: chunked]}

    loginCache.getHostSupportsGerritAuth(); returns false
    updateGerritAuthWhenRequired(httpContext, client); returns Optional.absent()
    authData.isLoginAndPasswordAvailable(); returns true
    "/a" is appended


please note:

* loginCache.getHostSupportsGerritAuth() returns false in second call
* httpContext in first call contains: http.auth.credentials-provider={<any realm>=[principal: gerrit-user]}
* GERRIT_AUTH_PATTERN doesn't match Set-Cookie: GerritAccount=aTEfprtxq3uQlwkXo32fQy67EUUDzXSl6a;Path=/
* Cookies / Timestamps don't match as it was run several times.

**Comment by SpOOnman** [comment]
Thanks @imsandli ! Maybe it would be easier for @uwolfer now!

**Comment by uwolfer** [comment]
Thank you very much. I will look into it ASAP.

**Comment by uwolfer** [comment]
I think this is probably fixed already in gerrit-rest-java-client, but sputnik does not use the latest version (commit: https://github.com/uwolfer/gerrit-rest-java-client/commit/1b2af223d2b0dffb4dff266f92007e3c1fdbf04e).

Could you please try to replace (make sure you remove the old one, but keep a backup in case it fails because of incompatibility) the jar in your sputnik lib folder with a new one: http://central.maven.org/maven2/com/urswolfer/gerrit/client/rest/gerrit-rest-java-client/0.8.5/gerrit-rest-java-client-0.8.5.jar

@tigerlcq: Are you using username / password from Apache auth file or from Gerrit settings "HTTP Password" of that user?

@SpOOnman: You are right, the URL is not posted in debug output. This could probably be improved. One question just to make sure: sputnik requests are synchronous (i.e. not done in multiple threads)?

**Comment by imsandli** [comment]
I can confirm that it works with gerrit-rest-java-client-0.8.5.jar

**Comment by SpOOnman** [comment]
@uwolfer yes, all Sputnik calls are synchronous. Sputnik uses only one thread. Some processor might use many threads internally.

**Comment by tigerlcq** [comment]
It works for me with this update, thank you

**Comment by pjagielski** [comment]
Ok, we'll release 1.5.1 today
