### ISSUE TITLE
Sonar does not evaluate Test coverage

### ISSUE THREAD

**Issue by lhug** [TouK/sputnik#115]
We are using Sputnik 1.5.0 to run a quick Sonar-check on our commits, to prevent having to check and reevaluate the entire project in sonar. While running gradle, the JUnit testresults are being created (with TEST-*.xml as name), as are the jacoco testresults with the correct name in the correct directories.
During Analysis, we get the following Warning:
`09:05:58.843 WARN  - You are not using the latest JaCoCo binary format version, please consider upgrading to latest JaCoCo version.`
quickly followed by
`09:05:58.933 INFO  - No information about coverage per test.`

We already tried changing the paths for sonar.tests to the binaries instead of the classes, this leads to FileNotFound-errors.
The sonar-project.properties are generated with the Sonar Gradle-Plugin via extracted task and we are using the SonarQube JavaPlugin Version 3.5, which seems to have JaCoCo embedded.

Since no ammount of googling could help me, and there seems no answer in the docs for this, we have to use this way.

**Comment by lhug** [comment]
Just to clarify: A full sonar-test using the sonar dashboard gives violations due to the fact that less than 65% of a certain class are not covered by unit tests. Sputnik reports no such violations even though it uses the same ruleset. Maybe this helps in finding a solutions, because frankly, we are quite confused.

**Comment by MarcusSjolin** [comment]
These two issues are indeed confusing, and should probably be resolved or explained. Bump.

**Comment by SpOOnman** [comment]
So you have an error during JaCoCo analysis which is rum by Sonar? If so, isn't it a Sonar issue not Sputnik's?

**Comment by lhug** [comment]
No - the problem was, that we could use our gradle Task and everything to analyze the projects, and they were evaluated as expected. When using sputnik for the (as I believe) exact same thing, there was no test coverage evaluated.

Which is why we were confused, if that had been a sonar-issue, the same would have had to have happened when pushing direclty via gradle task, but it did not.

Since we delayed sonar usage indefinitely, this issue may be ignored, marked as unresolvable or whatnot =)

**Comment by SpOOnman** [comment]
I've dropped support for SonarQube incremental analysis on 2.0.
