### ISSUE TITLE
Java 1.7 -> Java 1.8

### ISSUE THREAD

**Issue by pivovarit** [TouK/sputnik#138]
Guys, have you considered migrating to Java 1.8?

**Comment by SpOOnman** [comment]
Yes, there was even a PR with that. At that moment we've dropped it since some older installations might still use Java 7. It's a year later and Java 7 is EOL so I guess we can migrate to Java 8 with major release.

**Comment by pjagielski** [comment]
We plan to switch to Java 8 in 2.x release

**Comment by SpOOnman** [comment]
The 2.0 release is coming! I've already set source and target compatibility to 1.8 in develop branch, so I'm closing this issue! :)
