### ISSUE TITLE
Support SonarQube >=5.4

### ISSUE THREAD

**Issue by AndreasPelzer** [TouK/sputnik#161]
We have been trying to use Sputnik with SonarQube 5.4 or newer. However, this fails e.g. because  the mode "incremental" is not available anymore. Are there any plans to update Sputnik to an up to date version of SonarQube?

**Comment by SpOOnman** [comment]
If incremental option is not available anymore is there any chance or mode Sputnik might work? Can you do some research on SonarQube sources?

**Comment by knesenko** [comment]
Seems like its impossible to work with Sonar > 5.2. Any idea when sputnik is going to support Sonar > 5.2 ?

**Comment by SpOOnman** [comment]
Time has passes and it looks like SonarQube won't support incremental analysis anymore: https://community.sonarsource.com/t/incremental-scan-in-sonarqube-6-7-x/4210

I plan to deprecate and drop SonarQube support in a near future.

**Comment by SpOOnman** [comment]
I've dropped support for SonarQube incremental analysis on 2.0.
