### ISSUE TITLE
Sputnik does not support new tslint 

### ISSUE THREAD

**Issue by bjanczak** [TouK/sputnik#176]
Since April 2016 when 
`pl.touk.sputnik.processor.tslint.json.TSLintFileInfo`
was implemented tslint introduced new properties to JSON output. Those properties are:
- fix,
- ruleSeverity

Current version of sputnik fails to deserialize new tslint output:

`12:15:03 [Checkout code & Build PPM] Exception in thread "main" pl.touk.sputnik.processor.tslint.TSLintException: Error when converting from json format
12:15:03 [Checkout code & Build PPM]    at pl.touk.sputnik.processor.tslint.TSLintResultParser.parse(TSLintResultParser.java:39)
12:15:03 [Checkout code & Build PPM]    at pl.touk.sputnik.processor.tools.externalprocess.ProcessorRunningExternalProcess.process(ProcessorRunningExternalProcess.java:22)
12:15:03 [Checkout code & Build PPM]    at pl.touk.sputnik.engine.ReviewRunner.review(ReviewRunner.java:25)
12:15:03 [Checkout code & Build PPM]    at pl.touk.sputnik.engine.Engine.run(Engine.java:40)
12:15:03 [Checkout code & Build PPM]    at pl.touk.sputnik.Main.main(Main.java:36)
12:15:03 [Checkout code & Build PPM] Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "ruleSeverity" (class pl.touk.sputnik.processor.tslint.json.TSLintFileInfo), not marked as ignorable (5 known properties: "endPosition", "ruleName", "failure", "name", "startPosition"])
12:15:03 [Checkout code & Build PPM]  at [Source: java.io.StringReader@6b9267b; line: 1, column: 395] (through reference chain: pl.touk.sputnik.processor.tslint.json.TSLintFileInfo["ruleSeverity"])
12:15:03 [Checkout code & Build PPM]    at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:51)
12:15:03 [Checkout code & Build PPM]    at com.fasterxml.jackson.databind.DeserializationContext.reportUnknownProperty(DeserializationContext.java:671)
12:15:03 [Checkout code & Build PPM]    at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:761)
12:15:03 [Checkout code & Build PPM]    at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1297)
12:15:03 [Checkout code & Build PPM]    at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1275)
12:15:03 [Checkout code & Build PPM]    at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:247)
12:15:03 [Checkout code & Build PPM]    at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:118)
12:15:03 [Checkout code & Build PPM]    at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:227)
12:15:03 [Checkout code & Build PPM]    at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:204)
12:15:03 [Checkout code & Build PPM]    at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:23)
12:15:03 [Checkout code & Build PPM]    at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:2986)
12:15:03 [Checkout code & Build PPM]    at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2091)
12:15:03 [Checkout code & Build PPM]    at pl.touk.sputnik.processor.tslint.TSLintResultParser.parse(TSLintResultParser.java:30)
12:15:03 [Checkout code & Build PPM]    ... 4 more`

Request for improving `pl.touk.sputnik.processor.tslint.TSLintResultParser` so that it ignores parameters if unknown:
`objectMapper.configure(DeserializationConfig.Feature.FAIL_ON_UNKNOWN_PROPERTIES, false);`

**Comment by bjanczak** [comment]
What should I do to get pull request privileges in order to fix this issue?

**Comment by pjagielski** [comment]
Hey, thanks for submission. You should fork this repo to submit a PR

**Comment by bjanczak** [comment]
Pull request added.

**Comment by SpOOnman** [comment]
Fixed by #177.
