### ISSUE TITLE
Migrate to spotbugs

### ISSUE THREAD

**Issue by marquiswang** [TouK/sputnik#189]
According to the findbugs github and mailing list, findbugs is abandoned and development has switched to a fork named spotbugs. It appears to be fully backwards compatible with findbugs, so we just need to switch the dependency to:

```
<dependency>
  <groupId>com.github.spotbugs</groupId>
  <artifactId>spotbugs</artifactId>
  <version>3.1.3</version>
</dependency>
```

**Comment by christophercolumbusdog** [comment]
This should be an easy migration that would be really valuable! Has there been any work towards this?

**Comment by SpOOnman** [comment]
Sputnik has migrated to SpotBugs, this issue can be closed.
