### ISSUE TITLE
No Java Lint Plugin?

### ISSUE THREAD

**Issue by ambition-consulting** [TouK/sputnik#191]
Hi there,

you have Lint plugins for all kind of languages. I wonder why there is none for [Java](https://www.javaworld.com/article/2073587/javac-s--xlint-options.html)? Equally, I wonder why there is no way to export maven compiler warnings from the console? 

I just wonder if this is already possible somehow.

Regards
John

**Comment by SpOOnman** [comment]
I think there is no Lint plugin for Java as most developers use some IDE that lint code themselves or on demand. IDEs support incremental and complete compilation so many times programmer doesn't even execute Maven as compilation errors are highlighted and print to message window.

**Comment by ambition-consulting** [comment]
Tight IDE integration is a reality, but compilers distinguish between errors and warning, and in the context of reviewing such warnings, sometimes those are allowed to pass, sometimes they should be declined - hence the nature of them not being errors, which cannot pass. For that, visibility of such warnings in Gerrit would be advantageous.

**Comment by SpOOnman** [comment]
If I understand you correctly you want to display compiler warnings and errors as Gerrit comments?

**Comment by ambition-consulting** [comment]
Ideally, anything in the syntax of a compiler warning/error on the console should be possible to get displayed in Gerrit.  

- In the project I currently work in, a lot of commits get rejected due to IDE warnings. For the reviewer to see those, he has to check out the code and compile it in the IDE first.
- We are using another tool for java code quality - https://jqassistant.org/. They also display their errors as warnings in maven builds, using the same syntax that the maven compiler uses for warnings.

In theory, we could also extract this kind of functionality into some sort of generic GREP plugin - where some file containing the console build output is scanned for patterns, and displayed in Gerrit using some naming convention. I understand this is different to current plugins, which seem to be based on the analysis of each file. Thus there would be the challenge of identifying, which file a template match belongs to.

**Comment by SpOOnman** [comment]
I can see many ideas in your post. First one is a compiler. If you want compiler warning in Gerrit you need to run this compile, gather output and post it to Gerrit. It is possible, but may be tricky to run javac from running java process. You don't have dependencies in place, you'd need to use maven or gradle for this, some variables my be different, etc.

As for your project - can you recreate compiler warnings as Checkstyle, PMD or SpotBugs rules? This way static analysis of your code would match your IDE warnings. At least make it close.

Third idea is your jqassistant tool. You can run external tools with Sputnik and gather their output too. So you'd need some code at Sputnik to gather this output. This would require a PR from you I guess.
