### ISSUE TITLE
Allow running on commit instead of patchset

### ISSUE THREAD

**Issue by marquiswang** [TouK/sputnik#195]
It would be nice to have the option of running sputnik checks before actually creating a change in gerrit. I have my project set up so that sputnik (along with tests) is automatically run for new changes. However, sometimes it would be nice to just run it quickly before pushing a change to gerrit.

Can we add an option to pass in a commit (or just always run again HEAD), not require a changeId/patchset, and just print comments to stdout? We can call it quiet mode or offline mode or something.

**Comment by SpOOnman** [comment]
I think you would need an implementation of a ConnectorFacade that fetches changes with a commit hash and an implementation of a ReviewPublisher - that "publishes" changes to stdout. Then you could use some hook with your script to execute it.

What do you think?

**Comment by marquiswang** [comment]
Yeah, that sounds about right.
