### ISSUE TITLE
ReviewInput tag support for Gerrit connector

### ISSUE THREAD

**Issue by atavakoliyext** [TouK/sputnik#200]
Please provide a way to set the tag for the review comments to Gerrit (see the `tag` field of [ReviewInput](https://gerrit-review.googlesource.com/Documentation/rest-api-changes.html#review-input).

The motivation is to be able to set an appropriate "autogenerated:..." value (e.g. "autogenerated:sputnik"), when using Sputnik from CI, as described in the link above:

> Apply this tag to the review comment message, votes, and inline comments. Tags may be used by CI or other automated systems to distinguish them from human reviews. Votes/comments that contain tag with 'autogenerated:' prefix can be filtered out in the web UI.

Ideally, the exact tag would be configurable via the properties file.

**Comment by SpOOnman** [comment]
This was resolved with #172 and #198.
