### ISSUE TITLE
Feature Request - run analysis only on ew files

### ISSUE THREAD

**Issue by vitas** [TouK/sputnik#204]
Would be great to have an option to run analysis only on new files in the patch set.
Working with legacy code is not easy and developers cannot fix old issues due extensive regression testing

**Comment by marquiswang** [comment]
There is a configuration toggle `global.commentOnlyChangedLines` which prevents sputnik from commenting on any line that wasn't touched.

**Comment by vitas** [comment]
unfortunately, I'm getting this error (i use gerrit connection)
This connector does not support global.commentOnlyChangedLines

**Comment by SpOOnman** [comment]
@vitas I've released Sputnik 2.1.0 today which supports commentOnlyChangedLines for Gerrit. I hope this helps!

**Comment by vitas** [comment]
awesome! thank you , guys!

**Comment by SpOOnman** [comment]
You're welcome!

**Comment by vitas** [comment]
i have replaced jar file with new one in lib folder, but getting error:
Error: Could not find or load main class pl.touk.sputnik.Main

Do I something wrong?

**Comment by vitas** [comment]
I use java8 on linux, Sputnik 2.0.0
I have removed old jar file: sputnik-2.0.0.jar and put new one 2.1.0 into lib folder and run the analysis

**Comment by vitas** [comment]
I found the issue: i have to change jar file name also in shell script "sputnik" as it specified in CLASSPATH
So everything works! thank you

**Comment by SpOOnman** [comment]
Thanks for a solution!
