### ISSUE TITLE
ErrorProne support

### ISSUE THREAD

**Issue by marquiswang** [TouK/sputnik#207]
Would be nice to include support for https://errorprone.info

**Comment by SpOOnman** [comment]
Thanks for this! I can see that it is distributed as a jar in maven. Definitely it can be achieved!

**Comment by SpOOnman** [comment]
I've read documentation for errorprone and it looks like Sputnik cannot use it at the moment. Errorprone plugs in to compilation phase, while Sputnik works on source files (e.g. with .java extension) or compiled files (e.g. with .class extension) after that. Sputnik does not compile files and cannot use it.
