### ISSUE TITLE
Option global.commentOnlyChangedLines=true still provides negative score for old code

### ISSUE THREAD

**Issue by vitas** [TouK/sputnik#208]
I believe that is a bug in 2.1.0
Using new option in Gerrit global.commentOnlyChangedLines=true

INFO  p.t.s.c.gerrit.GerritCommentFilter - Query all file diffs to only include comments on modified lines
It founds some errors and makes -1 for review, but there are no comments as they are excluded (errors found not in new or modified code lines)

Comment excluded in file...
Comment excluded in file...
etc, etc

Summary: errors are excluded as comments but still counted for the final score

**Comment by SpOOnman** [comment]
You're right @vitas . Thanks for report, I'll fix that shortly.

**Comment by vitas** [comment]
I have tried latest revision, the issue is not fixed

**Comment by zhang3r** [comment]
I'm running into something really similar to this. where the summary still states `2 violation found` but the comments are being ignored. I think this is due to totalViolationCount not being decremented. I don't think this particular fix would fix my issue.

**Comment by SpOOnman** [comment]
I've just released Sputnik 2.2.0. Fix is included in this release. Please check if it works in your cases. Thanks!

**Comment by vitas** [comment]
I do not think it is fixed, as i already compiled and tested master branch with merged: "Move Gerrit comment filter to after visitor (#211)"

**Comment by SpOOnman** [comment]
@vitas thanks for your report! I've managed to fix this and I've just released https://github.com/TouK/sputnik/releases/tag/sputnik-2.2.1. I've tested it and it is resolved now. Please give me your feedback if it works fine for you. Thanks!

**Comment by vitas** [comment]
> @vitas thanks for your report! I've managed to fix this and I've just released https://github.com/TouK/sputnik/releases/tag/sputnik-2.2.1. I've tested it and it is resolved now. Please give me your feedback if it works fine for you. Thanks!

thank you, seems it works now!
