### ISSUE TITLE
Feature request: Support HTTP Passwords for Gerrit

### ISSUE THREAD

**Issue by corebonts** [TouK/sputnik#220]
New gerrit-rest-java-client supports HTTP password token that is defined in Settings -> HTTP Password page.
It can be useful if you don't want to use the regular site password.

See the corresponding pull request there:
https://github.com/uwolfer/gerrit-rest-java-client/pull/70

**Comment by corebonts** [comment]
I have commits for it but I want to do further testing before making the pull request.

**Comment by SpOOnman** [comment]
It is fixed in #230 and released with 2.6.0.
