### ISSUE TITLE
Error when using extended changeIds containing project and branch

### ISSUE THREAD

**Issue by corebonts** [TouK/sputnik#221]
When a cherry-pick is done and there are more commits with the same changeId, an exended id can be used to distinguish between the,

It has a format `project/subproject~branch/subbranch~changeId` (tilde separated)

If this is not encoded but just put in the URL, an error message comes from the server like:
`Request not successful. Message: Not Found. Status-Code: 404. Content: Not found: project`

**Comment by SpOOnman** [comment]
It is fixed in #230 and released with 2.6.0.
