### ISSUE TITLE
Distribution Zip File highly apreciated

### ISSUE THREAD

**Issue by patbaumgartner** [TouK/sputnik#223]
Hi,

I love sputnik and have used it in the past for our Jenkins and Gerrit setup. Since the newest release I miss the distribution ZIP file which contains everything. Since 2.2.2 everything easy available in the RELEASES section in Github but just realized that this is missing. Could you please add it again? It would make upgrading way easier. 

THANKS, Patrick

**Comment by corebonts** [comment]
If that's ok, it's available via maven central, for example:
[sputnik 2.2.3](https://search.maven.org/remotecontent?filepath=pl/touk/sputnik/2.2.3/sputnik-2.2.3.zip)

**Comment by patbaumgartner** [comment]
That's awesome! 

Is there a good way to link it in the README.md? It should be somehow documented in the first few lines in the repo.

Thanks!

**Comment by corebonts** [comment]
Actually I'm not sure whether it was intentional that it's not available on github, so I would leave your issue here until the owner responses.
For now consider my previous reply as a workaround.

**Comment by patbaumgartner** [comment]
hey @SpOOnman, any thoughts on my issue and documentation update?

**Comment by SpOOnman** [comment]
Hey @patbaumgartner . Sorry for my inactivity. I've released Sputnik 2.3.0 yesterday and I've just added some assets. Please see https://github.com/TouK/sputnik/releases/tag/sputnik-2.3.0 if that is sufficient for you?

**Comment by patbaumgartner** [comment]
Thank you very much, that helps a lot. 

I made a pull request with the documentation change which goes to maven central. That's fine for me as well, but it was not documented. Not sure how your release process looks like :)

**Comment by SpOOnman** [comment]
Thanks!

I've commented on your PR. My release process is purely manual so it was
probably my mistake.

Regards,
Tomasz

pt., 13 lis 2020 o 15:21 Patrick Baumgartner <notifications@github.com>
napisał(a):
