### ISSUE TITLE
Findbugs reports error in line -1

### ISSUE THREAD

**Issue by zdanek** [TouK/sputnik#33]
Which cannot be accepted by Gerrit and fails to POST comments

09:45:06.324 [main] INFO  p.t.s.c.gerrit.GerritConnector - Setting review {"message":"Total 5 violations found","labels":{"Code-Review":1},"comments":{"assembler/ServiceStub.java":[{"message":"[Checkstyle] ERROR: Unused import - java.util.MissingFormatArgumentException.","line":7},{"message":"[PMD] INFO: Avoid unused imports such as 'java.util.MissingFormatArgumentException'","line":7},{"message":"[PMD] INFO: Avoid unused private fields such as 'test2'.","line":13},{"message":"[PMD] ERROR: Avoid throwing raw exception types.","line":24},{"message":"[FindBugs] INFO: UuF: Unused field: assembler.ServiceStub.test2","line":-1}]}}
09:45:06.326 [main] INFO  p.t.s.connector.http.HttpConnector - Request  2: POST to http://gerrit.xxx.com:8080/a/changes/I53418fde285f73d078dff279490858e9dc9e6d42/revisions/f1e100c1a399160f2e0390b5824c1f630505ca73/review?
09:45:06.361 [main] INFO  p.t.s.connector.http.HttpConnector - Response 2: HTTP/1.1 400 Bad Request
09:45:06.361 [main] INFO  p.t.s.connector.http.HttpConnector - Entity 2: negative line number -1 not allowed on assembler/ServiceStub.java

**Comment by gildur** [comment]
I've submitted pull request to fix this problem: https://github.com/TouK/sputnik/pull/80

**Comment by SpOOnman** [comment]
#80 is merged.
