### ISSUE TITLE
Pull quality profiles from Sonarqube

### ISSUE THREAD

**Issue by marquiswang** [TouK/sputnik#36]
Instead of manually downloading quality profiles from Sonarqube and pointing sputnik's gerrit.config at the files, it would be nice to automatically download them straight from:

http://<sonarurl>/profiles/export?format=checkstyle&language=java&name=<profilename>
http://<sonarurl>/profiles/export?format=findbugs&language=java&name=<profilename>
http://<sonarurl>/profiles/export?format=pmd&language=java&name=<profilename>

You'll need basic authentication, but otherwise it should be easy.

**Comment by SpOOnman** [comment]
I think you should do this in pre-build step in your CI server. Sputnik should be only responsible for analysis.
