### ISSUE TITLE
Use gerrit-rest-java-client?

### ISSUE THREAD

**Issue by uwolfer** [TouK/sputnik#52]
I have just found this project and it looks really nice.

After shortly looking into the codebase, I think a lot of code could be simplified / removed when you would use my Gerrit REST API client library: https://github.com/uwolfer/gerrit-rest-java-client

What do you think? It is not deployed yet in a public maven repository, but if there is interest in it, I could do it. At the moment I only use this lib for my IntelliJ Gerrit plugin.

**Comment by SpOOnman** [comment]
@uwolfer are you interested into submitting PR that replaces current gerrit communication with your library?

**Comment by uwolfer** [comment]
@SpOOnman: Yes, I think I'll do that. I have released the lib as maven dependency some days ago.

**Comment by zygm0nt** [comment]
Closing, since this is already merged into master.
