### ISSUE TITLE
shouldThrowWhenNoSonarFiles does not pass

### ISSUE THREAD

**Issue by damianszczepanik** [TouK/sputnik#64]
When cloning fresh repo and running "gradle test" then I get following error:

pl.touk.sputnik.processor.sonar > SonarRunnerTest
shouldThrowWhenNoSonarFiles
java.lang.AssertionError: Expected exception: java.io.IOException

**Comment by SpOOnman** [comment]
I've checked with 15da54a as master. Works fine for me. My configuration:

-> gradle --version

------------------------------------------------------------
Gradle 2.2.1
------------------------------------------------------------

Build time:   2014-11-24 09:45:35 UTC
Build number: none
Revision:     6fcb59c06f43a4e6b1bcb401f7686a8601a1fb4a

Groovy:       2.3.6
Ant:          Apache Ant(TM) version 1.9.3 compiled on December 23 2013
JVM:          1.7.0_40 (Oracle Corporation 24.0-b56)
OS:           Linux 3.13.0-30-generic amd64

Can you please recheck?

**Comment by SpOOnman** [comment]
@damianszczepanik is this issue still relevant or is it fixed on your setup?

**Comment by damianszczepanik** [comment]
Currently three test fail and that's rather not the gradle problem but Unix/Windows end of line character

    GerritFacadeTest. shouldNotListDeletedFiles
    GerritFacadeTest. shouldParseListFilesResponse
    SonarRunnerTest. shouldThrowWhenNoSonarFiles

**Comment by SpOOnman** [comment]
@damianszczepanik can you provide a fix that works both on linux and Windows? I use only linux so I can't validate that.

**Comment by SpOOnman** [comment]
@damianszczepanik is this still relavant? Have you worked this out?

**Comment by damianszczepanik** [comment]
IT has been fixed in other PR that AFAIR was not merged

**Comment by SpOOnman** [comment]
Can you find that PR?
