### ISSUE TITLE
CppCheck support

### ISSUE THREAD

**Issue by JKrag** [TouK/sputnik#85]
Hi TouK
I am helping a customer running Gerrit, and have set up sputnik on some of their Java projects with great success, but many projects here are embedded C, so I would love to have CppCheck support as well. (http://cppcheck.sourceforge.net/)
I was wondering if you have any (internal?) documentation describing how to support another static analysis tool? If so, I might have a crack at it. But I would definitely welcome any support I could get.
Regards Jan

**Comment by SpOOnman** [comment]
Hi

We have no internal documentation how to run external processes, however this is doable.

There is one problem with CppCheck that it's Windows specific. When you run it you must parse results  to Sputnik format. Does it output to console or to file?

**Comment by JKrag** [comment]
CppCheck should also be available on Linux (http://linux.die.net/man/1/cppcheck) and on Mac OSX e.g. via brew install. 

I'll get back to you tomorrow regarding output format (out of town today).
/Jan

**Comment by JKrag** [comment]
Hi Tomasz
A bit more info on CppCheck format.
CppCheck by default outputs to console, on the usual unix philosophy that you can alwasy pipe to a file if you want.
It supports, as far as I can find:

1. an old "deprecated" xml output format (called type 1)
2. a new recommende xml output that you get by passing --xml-version=2 as an argument. The xml-2 format is documented in the manual (from page 7): http://cppcheck.sourceforge.net/manual.pdf
There is a CppCheck Jenkins plugin for parsing and displaying output. I guess that https://github.com/jenkinsci/cppcheck-plugin/blob/master/src/main/java/org/jenkinsci/plugins/cppcheck/parser/CppcheckParser.java should provide good inspiration for the parsing job :-)
3. Custom formats by passing a `--template=""` argument. E.g. ` --template="{file},{line},{severity},{id},{message}"`. There are also some predefined templates, but the only ones I have found mentioned are "vs", and "gcc" for Visual studio and gcc type output.

**Comment by JKrag** [comment]
As an example, I currently run CppCheck on shell from a Jenkins job on the whole project (i.e. no Gerrit interaction), with:
`cppcheck -j 4 --enable=all --force --xml-version=2 -i<ignore_this_dir> -iUnitTest .  2> cppcheck.xml`

outputting the result to a cppcheck.xml file which the Jenkins CppCheck plugin can parse to display results.

**Comment by SpOOnman** [comment]
I know this is an old issue. After review I think that if you're still interested please submit a PR with CppCheck integration. I, for myself, won't have time to implement this one for Sputnik.
