### ISSUE TITLE
Be able to specify the vote label and value

### ISSUE THREAD

**Issue by polopi** [TouK/sputnik#90]
Hello,

For now, as I experimented it a little, the sputnik user only post Code-Review+1/-1 on a patchset.
It would be nice to be able to specify the label and value of the vote. i.e. Verified+1

**Comment by SpOOnman** [comment]
You can do it, but it's not yet documented. There are various options like score.strategy, score.passingKey and others. Check it out in source code: https://github.com/TouK/sputnik/blob/master/src/main/java/pl/touk/sputnik/configuration/GeneralOption.java

This issue should be closed as soon as it's documented.

**Comment by SpOOnman** [comment]
I've created wiki page including these instructions: https://github.com/TouK/sputnik/wiki/Gerrit-configuration. Please review.

**Comment by polopi** [comment]
LGTM :) Thanks for the update
